### GET request to read all users
GET http://localhost:3000/api/v2/users

### POST request to create a new user
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
    "username": "ai2",
    "email": "ai2@example.com",
    "password": "pass12345",
    "role": "admin"
}

### DELETE request to delete a user
DELETE http://localhost:3000/api/v2/users/695f33650b8c95f3fdb3ecec

### POST Login a user
POST http://localhost:3000/api/v2/users/auth/cookie/login
Content-Type: application/json

{
    "email": "ai2@example.com",
    "password": "pass12345"
}

### POST Logout a user
POST http://localhost:3000/api/v2/users/auth/cookie/logout

### GET check user authentication
GET http://localhost:3000/api/v2/users/auth/cookie/me

### Ask AI
POST http://localhost:3000/api/v2/users/auth/ai/ask
Content-Type: application/json

{
    "question": "i like tan",
    "topK": 5
}